stages:
  - deploy

publish_to_github:
  stage: deploy
  image: debian:13-slim
  only:
    - tags

  before_script:
    - apt-get update && apt-get install -y git
    - git config --global user.name "GitLab CI"
    - git config --global user.email "gitlab-ci@garr.it"

  script:
    # Prepariamo il repository
    - git clone "$CI_REPOSITORY_URL" /tmp/ci-repo
    - cd /tmp/ci-repo
    - git checkout "$CI_COMMIT_TAG"

    # Pulizia
    - rm -rf ansible/inventories/ba1 ansible/inventories/pa1 ansible/inventories/ct1 docs .gitlab-ci.yml

    # Push su GitHub (con history)
    - '[ -z "$GITHUB_PAT" ] && echo "GITHUB_PAT is not set!" && exit 1 || echo "GITHUB_PAT is set"'
    - git remote add github "https://${GITHUB_PAT}@github.com/ConsortiumGARR/idem-certbot.git"
    - git add -A
    - git commit -m "$CI_COMMIT_MESSAGE"
    - git tag -f "$CI_COMMIT_TAG"
    - git push github HEAD:main --force
    - git push github "$CI_COMMIT_TAG" --force
    - git remote remove github

  after_script:
    - rm -rf /tmp/ci-repo
