# If you want to use Ansible locally
#localhost ansible_connection=local

# Inventory example
#[remote_hosts]
#<REMOTE_HOST> ansible_host=<IP_REMOTE_HOST>

[certbot_nodes]
controller ansible_host=90.147.188.199

[rsync_targets]
cnode1-pa1 ansible_host=90.147.189.22
cnode2-pa1 ansible_host=90.147.157.65
cnode3-pa1 ansible_host=90.147.189.71
cnode4-pa1 ansible_host=90.147.189.224
