services:
  idem-certbot:
    image: "{{ docker_image }}:{{ tag }}"
    container_name: "{{ container_name }}"
    hostname: "{{ hostname }}"
    env_file:
      - ".certbot.env"
    volumes:
      - "{{ certbot_data_volume }}:/etc/letsencrypt"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "certbot certificates > /dev/null 2>&1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s
