certbot_version: 3.0.0

email_admin: mario.dilorenzo@garr.it

domains: 
  - domain: mdx.idem.garr.it
    aliases: 
      - mdx.aai.garr.it
  - domain: md.idem.garr.it
    aliases: 
      - md.aai.garr.it
  - domain: eduid.aai.garr.it
    aliases: 
      - eduid-indire.aai.garr.it
  - domain: rt.idem.garr.it
    aliases: 
      - rt.aai.garr.it
  - domain: sp-demo.idem.garr.it
    aliases: []
  - domain: sp.aai-test.garr.it
    aliases: []
  - domain: conf.idem.garr.it
    aliases: 
      - conf.aai.garr.it
  - domain: idp.aai-test.garr.it
    aliases: []
  - domain: tcs-docs.aai.garr.it
    aliases: []
  - domain: mfa.idpcloud.garr.it
    aliases: []
  - domain: idm.idpcloud.garr.it
    aliases: []
  - domain: idp.idpcloud.garr.it
    aliases:
      - garr-idp-prod.idpcloud.garr.it
      - garr-idp-test.idpcloud.garr.it
      - idp-sicilia.idpcloud.garr.it
      - idp-dgnocchi.idpcloud.garr.it
      - idp-css.idpcloud.garr.it
      - idp-iccu.idpcloud.garr.it
      - idp-ssr.idpcloud.garr.it
      - idp-oasi.idpcloud.garr.it
      - idp-portici.idpcloud.garr.it
      - idp-emedea.idpcloud.garr.it
      - idp-cro.idpcloud.garr.it
      - idp-maugeri.idpcloud.garr.it
      - idp-srpisana.idpcloud.garr.it
      - idp-ifo.idpcloud.garr.it
      - idp-aux.idpcloud.garr.it
      - idp-inrca.idpcloud.garr.it
      - idp-scamillo.idpcloud.garr.it
      - idp-intna.idpcloud.garr.it
      - idp-istba.idpcloud.garr.it
      - idp-fbf.idpcloud.garr.it
      - idp-debellis.idpcloud.garr.it
      - idp-ismett.idpcloud.garr.it
      - idp-ieo.idpcloud.garr.it
      - idp-burlog.idpcloud.garr.it
      - idp-ospedalesanmartino.idpcloud.garr.it
      - idp-crob.idpcloud.garr.it
      - idp-isnb.idpcloud.garr.it
      - idp-sanmatteo.idpcloud.garr.it
      - idp-ccmonz.idpcloud.garr.it
      - idp-omp-mi.idpcloud.garr.it
      - idp-acs.idpcloud.garr.it
      - idp-gaslini.idpcloud.garr.it
      - idp-sdn.idpcloud.garr.it
      - idp-neuromed.idpcloud.garr.it
      - idp-slucia.idpcloud.garr.it
      - idp-stellamaris.idpcloud.garr.it
      - idp-iov.idpcloud.garr.it
      - idp-inmi.idpcloud.garr.it
      - idp-ior.idpcloud.garr.it
      - idp-multimedica.idpcloud.garr.it
      - idp-opbg.idpcloud.garr.it
      - idp-venezie.idpcloud.garr.it
      - idp-irst.idpcloud.garr.it
      - idp-bietti.idpcloud.garr.it
      - idp-candiolo.idpcloud.garr.it
      - idp-izs-sardegna.idpcloud.garr.it
      - idp-neurolesi.idpcloud.garr.it
      - idp-minsalute.idpcloud.garr.it
