email_rao: mario.dilorenzo@garr.it
certbot_version: 1.0.2

idem_rt_domain: rt.idem.garr.it
idem_rt_alias: rt.aai.garr.it

idem_mdx_domain: mdx.idem.garr.it
idem_mdx_1alias: mdx.aai.garr.it
idem_mdx_2alias: mdx.aai-test.garr.it
idem_mdx_3alias: mdx.idem-test.garr.it

eduid_idp_domain: eduid-indire.aai.garr.it

ippriv_second_cnode: 10.4.54.242
ippriv_third_cnode: 10.4.54.240
