[supervisord]
nodaemon=true
pidfile=/var/run/supervisord/supervisord.pid
user=root
; logfile=/dev/null
; logfile_maxbytes = 0
; loglevel=warn

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0777

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL for a unix socket

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:rsyslog]
command=/usr/sbin/rsyslogd -n
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
autorestart=true

[program:cron]
command=/usr/sbin/crond -f -l 8
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
autostart=true
autorestart=true

[program:certs]
command=/usr/local/bin/certs.sh
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
autorestart=false
startsecs=0
exitcodes=0
