# If you want to use Ansible locally
#localhost ansible_connection=local

# Inventory example
#[remote_hosts]
#<REMOTE_HOST> ansible_host=<IP_REMOTE_HOST>

[certbot_nodes]
controller ansible_host=10.4.54.100

[rsync_targets]
cnode1-ba1-r1 ansible_host=10.4.54.239
cnode1-ba1-r2 ansible_host=10.4.54.242
cnode1-ba1-r3 ansible_host=10.4.54.240
cnode1-ba1-r4 ansible_host=10.4.54.237
ba1-cnode-1 ansible_host=10.4.54.101
ba1-cnode-2 ansible_host=10.4.54.102
ba1-cnode-3 ansible_host=10.4.54.103
ba1-cnode-4 ansible_host=10.4.54.104
