# If you want to use Ansible locally
#localhost ansible_connection=local

# Inventory example
#[remote_hosts]
#<REMOTE_HOST> ansible_host=<IP_REMOTE_HOST>

[certbot_nodes]
controller ansible_host=90.147.184.43

[rsync_targets]
cnode1-ct1 ansible_host=90.147.166.136
cnode2-ct1 ansible_host=90.147.166.169
cnode3-ct1 ansible_host=90.147.184.51
cnode4-ct1 ansible_host=