services:
  idem-certbot:
    image: "gitlab.dir.garr.it:4567/idem/idem-certbot:{{ certbot_version }}"
    container_name: "idem-certbot"
    hostname: idem-certbot
    env_file:
      - ".idemcertbot.env"
    volumes:
      - /srv/idem-certbot/:/etc/letsencrypt
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "certbot certificates > /dev/null 2>&1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s
