- name: Ensure certbot user exists with home and bash shell
  ansible.builtin.user:
    name: certbot
    home: /home/certbot
    shell: /bin/bash
    create_home: true
    state: present

- name: Create Certbot folder
  ansible.builtin.file:
    path: "/opt/certbot-deploy"
    state: directory
    recurse: yes

- name: Generate DOMAINS_LIST string
  ansible.builtin.set_fact:
    domains_list: >-
      {{
        domains
        | map(attribute='domain') | zip(domains | map(attribute='aliases') | map('join', ',')) 
        | map('join', ':') 
        | map('regex_replace', ':$', '') 
        | join(';')
      }}

- name: Copy files from template
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/opt/certbot-deploy/{{ item }}"
  loop:
    - "docker-compose.yml"
    - ".idemcertbot.env"

- name: Run Certbot image
  ansible.builtin.shell: "docker compose pull && docker compose up -d"
  args:
    chdir: "/opt/certbot-deploy"

- name: Delete Certbot folder
  ansible.builtin.file:
    path: "/opt/certbot-deploy"
    state: absent

- name: Ensure .ssh directory exists for certbot
  ansible.builtin.file:
    path: "/home/certbot/.ssh"
    state: directory
    mode: '0700'
    owner: certbot
    group: certbot

- name: Copy SSH key pair for certbot user
  ansible.builtin.copy:
    src: "{{ item.name }}"
    dest: "/home/certbot/.ssh/{{ item.name }}"
    mode: "{{ item.mode }}"
    owner: certbot
    group: certbot
  loop:
    - { name: 'id_ed25519_certbot', mode: '0600' }
    - { name: 'id_ed25519_certbot.pub', mode: '0644' }

- name: Ensure /srv/idem-certbot directory has the right privileges
  ansible.builtin.file:
    path: "/srv/idem-certbot"
    state: directory
    owner: certbot
    group: certbot
    recurse: true

- name: Create Certbot Cron file for Rsync
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0755"
  loop:
    - { src: 'rsync_idem_certbot', dest: '/etc/cron.d/rsync_idem_certbot' }
    - { src: 'rsync_idem_certbot.sh.j2', dest: '/usr/local/bin/rsync_idem_certbot.sh' }