# If you want to use Ansible locally
#localhost ansible_connection=local

[remote_hosts]
#<REMOTE_HOST> ansible_host=<IP_REMOTE_HOST>

[pa1]
cnode1-pa1 ansible_host=90.147.189.22
cnode2-pa1 ansible_host=90.147.157.65
cnode3-pa1 ansible_host=90.147.189.71

[pa1-n1]
cnode1-pa1 ansible_host=90.147.189.22

[pa1-n2]
cnode2-pa1 ansible_host=90.147.157.65

[pa1-n3]
cnode3-pa1 ansible_host=90.147.189.71

[controller-pa1]
controller-pa1 ansible_host=90.147.188.199
