#localhost ansible_connection=local

[remote_hosts]
#<REMOTE_HOST> ansible_host=<IP_REMOTE_HOST>
#cnode1-ba1-r1.aai.garr.it ansible_host=10.4.54.239
#cnode1-pa1 ansible_host=90.147.189.22

[pa1-n1]
cnode1-pa1 ansible_host=90.147.189.22

[cnode1]
cnode1-ba1-r1.aai.garr.it ansible_host=10.4.54.239

