#localhost ansible_connection=local

[remote_hosts]
#<REMOTE_HOST> ansible_host=<IP_REMOTE_HOST>
cnode1-ba1-r1.aai.garr.it ansible_host=10.4.54.239

[cnode1]
cnode1-ba1-r1.aai.garr.it ansible_host=10.4.54.239

